# Generated by Django 4.0.3 on 2024-08-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=300)),
                ('landmark', models.CharField(max_length=300)),
                ('locality', models.CharField(max_length=300)),
                ('pincode', models.CharField(max_length=300)),
                ('landline_no', models.CharField(max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomsAndPatientName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('symptom_one', models.CharField(max_length=50)),
                ('symptom_two', models.CharField(max_length=50)),
                ('symptom_three', models.CharField(max_length=50)),
                ('symptom_four', models.CharField(max_length=50)),
                ('symptom_five', models.CharField(max_length=50)),
            ],
        ),
    ]
