# Generated by Django 4.0.3 on 2022-04-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyadrishti', '0002_sumptomandpatientname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('locality', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('landline_no', models.CharField(max_length=12)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=40)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=40)),
                ('altitude', models.DecimalField(decimal_places=20, max_digits=40)),
                ('type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
            ],
        ),
    ]
