# Generated by Django 4.0.3 on 2022-04-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyadrishti', '0007_alter_hospitals_landline_no_alter_hospitals_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='street',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
