# Generated by Django 4.0.3 on 2022-04-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyadrishti', '0008_hospitals_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='landmark',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
