# Generated by Django 4.0.3 on 2022-04-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divyadrishti', '0009_hospitals_landmark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SumptomAndPatientName',
            new_name='SymptomsAndPatientName',
        ),
        migrations.RenameField(
            model_name='symptomsandpatientname',
            old_name='patientName',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='symptomsandpatientname',
            old_name='symptomFive',
            new_name='symptom_five',
        ),
        migrations.RenameField(
            model_name='symptomsandpatientname',
            old_name='symptomFour',
            new_name='symptom_four',
        ),
        migrations.RenameField(
            model_name='symptomsandpatientname',
            old_name='symptomOne',
            new_name='symptom_one',
        ),
        migrations.RenameField(
            model_name='symptomsandpatientname',
            old_name='symptomThree',
            new_name='symptom_three',
        ),
        migrations.RenameField(
            model_name='symptomsandpatientname',
            old_name='symptomTwo',
            new_name='symptom_two',
        ),
        migrations.RenameField(
            model_name='symptomslist',
            old_name='symptomName',
            new_name='symptom_name',
        ),
    ]
